var CANVAS_WIDTH = 790;
var CANVAS_HEIGHT = 1400;

var EDGEBOARD_X = 140;
var EDGEBOARD_Y = 0;

var FONT = "gotham_boldregular";
var FONT1 = "RTWSYueGoTrial-Light";

var FPS_TIME      = 1000/24;
var DISABLE_SOUND_MOBILE = false;

var SKIER_X_START        = CANVAS_WIDTH/2;
var SKIER_Y_START        = 250;
var SKIER_WIDTH          = 232;
var SKIER_HEIGHT         = 142.4;
var SKIER_FALLING_WIDTH  = 93;
var SKIER_FALLING_HEIGHT = 180;

var TOLLERANCE = 1.5;
var DECELERATION = 1;
var DECELERATION_HITTED = -1;
var CHANGE_DIRECTION_FASTER = 1;
var MODIFIER = 15;
var ACCELERATION = 1;

var NUM_ROW;
var HEIGHT_BETWEEN_OBSTACLES = 300;

var NUM_ELEMENTS = 5;

var TREE_WIDTH   = 200;
var TREE_HEIGHT  = 221;
var TREE2_WIDTH  = 230;
var TREE2_HEIGHT = 252;
var ROCK_WIDTH   = 120;
var ROCK_HEIGHT  = 92;
var FENCE_WIDTH  = 126;
var FENCE_HEIGHT = 47;
var BONUS_WIDTH  = 116;
var BONUS_HEIGHT = 89;

var MAX_OBSTACLE_WIDTH  = TREE2_WIDTH;
var MAX_OBSTACLE_HEIGHT = TREE2_HEIGHT;

var SKIER_RECTANGLE_WIDTH   = 30;
var SKIER_RECTANGLE_HEIGHT  = 20;
var TREE_RECTANGLE_WIDTH    = 10;
var TREE_RECTANGLE_HEIGHT   = 20;
var TREE2_RECTANGLE_WIDTH   = 50;
var TREE2_RECTANGLE_HEIGHT  = 20;
var ROCK_RECTANGLE_WIDTH    = 150;
var ROCK_RECTANGLE_HEIGHT   = 10;
var FENCE_RECTANGLE_WIDTH   = 160;
var FENCE_RECTANGLE_HEIGHT  = 50;
var BONUS_RECTANGLE_WIDTH  = 70;
var BONUS_RECTANGLE_HEIGHT = 49;

var SKIER_SPD;
var OBSTACLES_SPD;
var SCORE_TO_ADD;
var SCORE_BONUS;
var MAX_OBJECT_FOR_TYPE;
var MIN_OBJECT_ROW;
var MAX_OBJECT_ROW;
var SCORE_FOR_INCREASE_SPD;
var SPEED_INCREASE;

var TREE   = 0;
var TREE2  = 1;
var ROCK   = 2;
var FENCE  = 3;
var BONUS  = 4;

var BG_GAME_INDEX       = 0;
var BG_GAME2_INDEX      = 1;
var BG_GAME3_INDEX      = 2;
var LINE_INDEX          = 3;
var SKIER_INDEX         = 4;
var OBSACLE_INDEX       = 5;
var SCORE_INDEX         = 6;
var BUTTON_INDEX        = 7;
var SKIER_FALLING_INDEX = 8;


var SKIER_TEMP = 9;



var STATE_LOADING = 0;
var STATE_MENU    = 1;
var STATE_HELP    = 1;
var STATE_GAME    = 3;

var ON_MOUSE_DOWN  = 0;
var ON_MOUSE_UP    = 1;
var ON_MOUSE_OVER  = 2;
var ON_MOUSE_OUT   = 3;
var ON_DRAG_START  = 4;
var ON_DRAG_END    = 5;
